name: study_companion
description: "A zero-cost, private, offline-first student companion."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # Navigation
  go_router: ^14.6.0

  # Database (Local)
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.5

  # UI & Theming
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.2
  gap: ^3.0.1

  # Utils
  intl: ^0.20.2
  uuid: ^4.5.1
  equatable: ^2.0.7
  llama_cpp_dart: ^0.1.2+1
  file_picker: ^8.0.0
  shared_preferences: ^2.2.0
  supabase_flutter: ^2.0.0
  flutter_local_notifications: ^19.5.0
  fl_chart: ^1.1.1
  http: ^1.6.0
  dio: ^5.9.0
  pdf: ^3.11.3
  printing: ^5.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  riverpod_generator: ^2.2.0
  isar_generator: ^3.1.0+1
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/app_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/models/

dependency_overrides:
  analyzer: ^5.13.0
